# Generated by Django 4.2.17 on 2025-01-03 16:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Austria', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('external_id', models.PositiveBigIntegerField(unique=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('standard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('is_available', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender_profile.address')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_user_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='TaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('external_id', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('standard_title', models.CharField(max_length=255, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('standard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender_profile.address')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_company_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
