# Generated by Django 4.2.17 on 2025-01-01 19:29

import django.contrib.postgres.fields
from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('external_id', models.PositiveBigIntegerField(unique=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('standard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_user_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('external_id', models.PositiveBigIntegerField()),
                ('occupation', models.TextField()),
                ('standard_occupations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_company_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
