# Generated by Django 4.2.17 on 2025-01-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprofile',
            name='standard_skills',
        ),
        migrations.RemoveField(
            model_name='taskprofile',
            name='standard_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='standard_skills',
        ),
    ]
