# Generated by Django 4.2.17 on 2025-01-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0001_initial'),
        ('recommender_profile', '0002_remove_taskprofile_standard_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprofile',
            name='standard_skills',
            field=models.ManyToManyField(related_name='task_profiles', to='recommender_kb.skill'),
        ),
        migrations.AddField(
            model_name='taskprofile',
            name='standard_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_profiles', to='recommender_kb.occupation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='standard_skills',
            field=models.ManyToManyField(related_name='user_profiles', to='recommender_kb.skill'),
        ),
    ]
