# Generated by Django 4.2.19 on 2025-03-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='broader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrower', to='recommender_kb.skill'),
        ),
    ]
