# Generated by Django 4.2.19 on 2025-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0002_skill_broader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='broader',
        ),
        migrations.AddField(
            model_name='skill',
            name='broader_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
