# Generated by Django 4.2.19 on 2025-03-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0003_remove_skill_broader_skill_broader_uri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ISCOGroup',
            new_name='SkillGroup',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='broader_uri',
        ),
        migrations.AddField(
            model_name='skill',
            name='broader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='recommender_kb.skillgroup'),
        ),
    ]
