# Generated by Django 4.2.19 on 2025-03-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0004_rename_iscogroup_skillgroup_remove_skill_broader_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='isco_group',
        ),
    ]
