# Generated by Django 4.2.19 on 2025-03-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_kb', '0005_remove_occupation_isco_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgroup',
            name='code',
        ),
    ]
