# Generated by Django 4.2.17 on 2025-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender_profile', '0003_taskprofile_standard_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasks', models.ManyToManyField(to='recommender_profile.taskprofile')),
                ('users', models.ManyToManyField(to='recommender_profile.userprofile')),
            ],
        ),
    ]
